'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, KeyRound, LockKeyhole, RefreshCw, Save, ServerCog } from 'lucide-react';

type CatalogItem={id:string;category:string;provider:string;displayName:string;capabilities:readonly string[];secretName:string};
type SavedIntegration={id:string;enabled:boolean;base_url?:string|null;model?:string|null;health_status?:string;secret_configured?:boolean;masked_hint?:string|null};
type IngestionCatalog={key:string;displayName:string;cadenceMinutes:number;batchSize:number};
type SavedIngestion={pipeline_key:string;enabled:boolean;cadence_minutes:number;batch_size:number;last_status?:string;last_run_at?:string|null};

export function AdminSuite(){
 const [session,setSession]=useState<{configured:boolean;authenticated:boolean}|null>(null); const [token,setToken]=useState(''); const [data,setData]=useState<any>(null); const [health,setHealth]=useState<any>(null); const [busy,setBusy]=useState(''); const [error,setError]=useState('');
 async function loadSession(){const r=await fetch('/api/admin/session',{cache:'no-store'});setSession(await r.json());}
 async function load(){setError('');const [a,h]=await Promise.all([fetch('/api/admin/settings',{cache:'no-store'}),fetch('/api/health',{cache:'no-store'})]);if(a.status===401){setSession(s=>s?{...s,authenticated:false}:s);return;}if(!a.ok){setError(`Admin settings HTTP ${a.status}`);return;}setData(await a.json());setHealth(await h.json().catch(()=>null));}
 useEffect(()=>{void loadSession()},[]); useEffect(()=>{if(session?.authenticated)void load()},[session?.authenticated]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy('login');setError('');const r=await fetch('/api/admin/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})});const j=await r.json().catch(()=>({}));setBusy('');if(!r.ok){setError(j.error??'Login failed');return;}setToken('');setSession({configured:true,authenticated:true});}
 async function logout(){await fetch('/api/admin/session',{method:'DELETE'});setData(null);setSession(s=>s?{...s,authenticated:false}:s);}
 if(!session)return <Panel title="Admin Suite"><span>Checking admin session…</span></Panel>;
 if(!session.configured)return <Panel title="Admin Suite"><div className="danger">MERCURY_ADMIN_TOKEN is not configured in the runtime. Admin access fails closed.</div></Panel>;
 if(!session.authenticated)return <Panel title="Admin Suite"><form onSubmit={login} style={{display:'grid',gap:10,maxWidth:460}}><div className="eyebrow">Protected operator access</div><h2>Unlock Mercury Administration</h2><p className="muted2">The token establishes an HttpOnly session. It is never stored in dashboard state.</p><input type="password" autoComplete="current-password" placeholder="Admin token" value={token} onChange={e=>setToken(e.target.value)} required/><button className="pulse-button" disabled={busy==='login'}><LockKeyhole size={16}/>{busy==='login'?'Authenticating…':'Unlock Admin Suite'}</button>{error&&<div className="danger">{error}</div>}</form></Panel>;
 if(!data)return <Panel title="Admin Suite"><RefreshCw className="spin" size={16}/> Loading protected configuration…</Panel>;
 const saved=new Map<string,SavedIntegration>((data.integrations??[]).map((x:SavedIntegration)=>[x.id,x])); const ingSaved=new Map<string,SavedIngestion>((data.ingestion??[]).map((x:SavedIngestion)=>[x.pipeline_key,x]));
 return <div style={{display:'grid',gap:14}}>
  <section className="section-head"><div><div className="eyebrow">Protected operator workspace</div><h2>Administration & Integrations</h2><p>LLMs → data providers → ingestion → monitoring. Secrets stay encrypted server-side.</p></div><div style={{display:'flex',gap:8}}><button className="icon-button" onClick={()=>void load()} aria-label="Refresh admin"><RefreshCw size={16}/></button><button className="icon-button" onClick={logout}>Lock</button></div></section>
  {error&&<div className="surface danger" style={{padding:12}}>{error}</div>}
  <section className="kpi-strip">{[['Database',health?.database?.reachable?'LIVE':'OFF'],['Schema',health?.database?.schemaReady?'READY':'WAIT'],['Vault',data.vaultConfigured?'READY':'MISSING'],['Admin session','LOCKED'],['Capital','DISABLED']].map(([a,b])=><div className="kpi" key={a}><span>{a}</span><strong className={b==='LIVE'||b==='READY'||b==='LOCKED'?'good':b==='DISABLED'?'warn':'danger'}>{b}</strong></div>)}</section>
  <section className="surface" style={{padding:16}}><div className="section-head"><div><h2>API & LLM Integrations</h2><p>Configure provider URLs, models and encrypted credentials.</p></div><KeyRound size={18}/></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(310px,1fr))',gap:12}}>{(data.catalog as CatalogItem[]).map(item=><IntegrationCard key={item.id} item={item} saved={saved.get(item.id)} vaultReady={data.vaultConfigured} onSaved={load}/>)}</div></section>
  <section className="surface" style={{padding:16}}><div className="section-head"><div><h2>Data Ingestion Control</h2><p>Enable pipelines and control cadence/batch size. This changes configuration only; execution remains under the protected workflow engine.</p></div><ServerCog size={18}/></div><div style={{display:'grid',gap:10}}>{(data.ingestionCatalog as IngestionCatalog[]).map(item=><IngestionCard key={item.key} item={item} saved={ingSaved.get(item.key)} onSaved={load}/>)}</div></section>
  <section className="hero-grid"><Monitor title="Runtime Diagnostics" route="/api/health"/><Monitor title="Market Provider Fabric" route="/api/providers/market/status"/><Monitor title="Open Data Mesh" route="/api/providers/open-data/status"/><Monitor title="Open Intelligence" route="/api/integrations/open-intelligence"/><Monitor title="Research Proof" route="/api/integrations/research-proof"/></section>
  <section className="surface" style={{padding:16}}><div className="section-head"><div><h2>Admin Audit Trail</h2><p>Recent configuration mutations. Secret values are never logged.</p></div><Activity size={18}/></div>{(data.audit??[]).length?(data.audit??[]).map((x:any,i:number)=><div className="source-row" key={i}><span>{new Date(x.created_at).toLocaleString()} · {x.action} {x.target_type}</span><b>{x.target_ref??'—'} · {x.outcome}</b></div>):<div className="muted2">No admin changes recorded yet.</div>}</section>
 </div>
}

function IntegrationCard({item,saved,vaultReady,onSaved}:{item:CatalogItem;saved?:SavedIntegration;vaultReady:boolean;onSaved:()=>Promise<void>}){const [enabled,setEnabled]=useState(saved?.enabled??false);const [baseUrl,setBaseUrl]=useState(saved?.base_url??'');const [model,setModel]=useState(saved?.model??'');const [secret,setSecret]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');async function save(){setBusy(true);setMessage('');const r=await fetch('/api/admin/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({type:'integration',value:{id:item.id,enabled,baseUrl,model,secret:secret||undefined,secretName:item.secretName}})});const j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setMessage(j.error??`HTTP ${r.status}`);return;}setSecret('');setMessage('Saved');await onSaved();}return <div className="mini-panel" style={{border:'1px solid var(--border, #263044)',borderRadius:10,padding:12}}><div className="section-head"><div><b>{item.displayName}</b><div className="tiny">{item.category} · {item.capabilities.join(' · ')}</div></div><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/></div>{item.category==='llm'&&<input placeholder="Model, e.g. gpt-5" value={model} onChange={e=>setModel(e.target.value)}/>} {(item.category==='service'||item.category==='llm')&&<input placeholder="Base URL (optional)" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)}/>}<input type="password" placeholder={saved?.secret_configured?`Credential configured ${saved.masked_hint??''} · enter to rotate`:vaultReady?'API key / credential':'Vault key missing in runtime'} value={secret} onChange={e=>setSecret(e.target.value)} disabled={!vaultReady}/><button className="pulse-button" onClick={save} disabled={busy}><Save size={14}/>{busy?'Saving…':'Save'}</button>{message&&<div className={message==='Saved'?'good':'danger'}>{message}</div>}</div>}
function IngestionCard({item,saved,onSaved}:{item:IngestionCatalog;saved?:SavedIngestion;onSaved:()=>Promise<void>}){const [enabled,setEnabled]=useState(saved?.enabled??false);const [cadence,setCadence]=useState(saved?.cadence_minutes??item.cadenceMinutes);const [batch,setBatch]=useState(saved?.batch_size??item.batchSize);const [busy,setBusy]=useState(false);async function save(){setBusy(true);await fetch('/api/admin/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({type:'ingestion',value:{pipelineKey:item.key,enabled,cadenceMinutes:Number(cadence),batchSize:Number(batch),sourcePriority:[]}})});setBusy(false);await onSaved();}return <div className="source-row" style={{gap:10,alignItems:'center'}}><span style={{flex:1}}><b>{item.displayName}</b><small style={{display:'block'}}>{saved?.last_status??'never_run'}{saved?.last_run_at?` · ${new Date(saved.last_run_at).toLocaleString()}`:''}</small></span><label className="tiny">On <input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/></label><label className="tiny">Cadence <input style={{width:78}} type="number" min={1} max={10080} value={cadence} onChange={e=>setCadence(Number(e.target.value))}/>m</label><label className="tiny">Batch <input style={{width:78}} type="number" min={1} max={10000} value={batch} onChange={e=>setBatch(Number(e.target.value))}/></label><button className="icon-button" onClick={save} disabled={busy}><Save size={14}/></button></div>}
function Monitor({title,route}:{title:string;route:string}){const [data,setData]=useState<any>(null);const [error,setError]=useState('');useEffect(()=>{fetch(route,{cache:'no-store'}).then(async r=>{const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error??`HTTP ${r.status}`);setData(j)}).catch(e=>setError(e.message))},[route]);const values=useMemo(()=>data?Object.entries(data).filter(([,v])=>typeof v!=='object').slice(0,7):[],[data]);return <div className="surface mini-panel"><h3>{title}</h3><div className="tiny">{route}</div>{error?<div className="danger">{error}</div>:values.length?values.map(([k,v])=><div className="source-row" key={k}><span>{k}</span><b>{String(v)}</b></div>):<div className="muted2">Loading / no scalar status.</div>}</div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="surface" style={{padding:18}}><h2>{title}</h2>{children}</section>}
