'use client';
import { useEffect,useMemo,useState } from 'react';
import { Activity,FlaskConical,RefreshCw,ShieldCheck,XCircle } from 'lucide-react';
import { PaperOrderTicket } from '@/components/paper-order-ticket';
import { PaperPerformancePanel } from '@/components/paper-performance-panel';
import { PaperRiskCenter } from '@/components/paper-risk-center';
type PaperOrder={id:string;symbol:string;market?:string|null;side:string;requested_qty:string|number;filled_qty:string|number;requested_price?:string|number|null;average_fill_price?:string|number|null;status:string;order_type?:string;time_in_force?:string;fee_amount?:string|number;latency_ms?:number|null;slippage_bps?:string|number|null;created_at:string};
type Position={id:string;symbol:string;market:string;quantity:number;averageCost:number;markPrice:number;marketValue:number;costBasis:number;unrealizedPnl:number;marked_at?:string|null};
type Account={name:string;startingCapital:number;cash:number;buyingPower:number;equity:number;marketValue:number;grossExposure:number;realizedPnl:number;unrealizedPnl:number;totalPnl:number;totalReturnPct:number;positions:Position[];capitalExecutionEnabled:false};
type TerminalData={ok:boolean;mode:'paper';capitalExecutionEnabled:false;brokerConnected?:false;evidenceScope?:string;error?:string;summary:{orders:number;filled:number;rejected:number;open:number;cancelled?:number};orders:PaperOrder[];latestPortfolioDecision?:Record<string,unknown>|null;account?:Account|null};
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v);
export function PaperTradingTerminal(){const[data,setData]=useState<TerminalData|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(true);const[tab,setTab]=useState<'overview'|'trade'|'positions'|'orders'|'performance'|'journal'|'risk'>('overview');async function load(){setLoading(true);setError('');try{const r=await fetch('/api/paper/terminal',{cache:'no-store'});const b=await r.json().catch(()=>({}));setData(b as TerminalData);if(!r.ok)setError(b.error??`HTTP ${r.status}`)}catch(e){setError(e instanceof Error?e.message:'Paper terminal failed to load')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);const orders=data?.orders??[];const account=data?.account;const recent=useMemo(()=>orders.slice(0,12),[orders]);const tone=(s:string)=>s==='rejected'?'danger':['filled','simulated'].includes(s)?'good':s==='cancelled'?'muted2':'warn';async function cancel(id:string){const r=await fetch(`/api/paper/orders/${encodeURIComponent(id)}`,{method:'DELETE'});if(!r.ok){const b=await r.json().catch(()=>({}));setError(b.error??`Cancel HTTP ${r.status}`)}await load()}async function resetAccount(){if(!window.confirm('Reset the virtual account to starting capital? Historical snapshots and journal records will be preserved.'))return;const r=await fetch('/api/paper/account/reset',{method:'POST'});if(!r.ok){const b=await r.json().catch(()=>({}));setError(b.error??`Reset HTTP ${r.status}`)}await load()}return <div className="paper-terminal">
<section className="paper-hero surface"><div><div className="eyebrow">Mercury execution research</div><h1>Paper Trading Terminal</h1><p>Persistent virtual account, lifecycle-aware paper orders, execution simulation and evidence analytics. No brokerage connection or real capital authority.</p></div><div className="paper-mode-badge"><FlaskConical size={16}/><div><b>PAPER MODE</b><small>REAL CAPITAL LOCKED</small></div></div></section>
<section className="paper-kpis"><div className="kpi"><span>Equity</span><strong>{loading?'…':account?money(account.equity):'—'}</strong><small>virtual account</small></div><div className="kpi"><span>Cash / Buying Power</span><strong>{loading?'…':account?money(account.cash):'—'}</strong><small>{account?money(account.buyingPower):'not available'}</small></div><div className="kpi"><span>Total P&amp;L</span><strong className={(account?.totalPnl??0)>=0?'good':'danger'}>{loading?'…':account?money(account.totalPnl):'—'}</strong><small>{account?`${account.totalReturnPct.toFixed(2)}%`:'—'}</small></div><div className="kpi"><span>Exposure</span><strong>{loading?'…':account?money(account.grossExposure):'—'}</strong><small>{account?.positions.length??0} positions</small></div><div className="kpi"><span>Open Orders</span><strong className="warn">{loading?'…':data?.summary.open??0}</strong><small>{data?.summary.cancelled??0} cancelled</small></div><div className="kpi"><span>Capital</span><strong className="warn">LOCKED</strong><small>broker off</small></div></section>
<div className="paper-toolbar"><div className="admin-tabs">{(['overview','trade','positions','orders','performance','journal','risk'] as const).map(i=><button key={i} className={tab===i?'active':''} onClick={()=>setTab(i)}>{i[0].toUpperCase()+i.slice(1)}</button>)}</div><button className="icon-button" onClick={()=>void load()} aria-label="Refresh paper trading"><RefreshCw size={16} className={loading?'spin':''}/></button></div>{error&&<div className="surface paper-warning"><b className="danger">Terminal warning:</b> {error}</div>}
{tab==='overview'&&<div className="paper-grid"><section className="surface paper-panel"><div className="section-head"><div><h2>Virtual Account</h2><p>Persistent paper ledger initialized once at $100,000.</p></div><Activity size={17}/></div>{account?<div className="paper-facts"><div><span>Starting capital</span><b>{money(account.startingCapital)}</b></div><div><span>Equity</span><b>{money(account.equity)}</b></div><div><span>Realized P&amp;L</span><b>{money(account.realizedPnl)}</b></div><div><span>Unrealized P&amp;L</span><b>{money(account.unrealizedPnl)}</b></div></div>:<Empty text="Account unavailable until paper-account migrations are applied."/>}</section><section className="surface paper-panel"><div className="section-head"><div><h2>Execution Boundary</h2><p>Safety state.</p></div><ShieldCheck size={17}/></div><div className="paper-facts"><div><span>Mode</span><b>PAPER</b></div><div><span>Broker</span><b>NONE</b></div><div><span>Capital execution</span><b>DISABLED</b></div><div><span>Evidence</span><b>{data?.evidenceScope??'LIVE-ONLY'}</b></div></div></section><section className="surface paper-panel paper-wide"><div className="section-head"><div><h2>Recent Paper Activity</h2><p>Non-validation records only.</p></div></div><OrderTable orders={recent} tone={tone} onCancel={cancel}/></section></div>}
{tab==='trade'&&<PaperOrderTicket onComplete={load}/>} 
{tab==='positions'&&<section className="surface paper-panel"><div className="section-head"><div><h2>Virtual Positions</h2><p>Marked to the latest warehouse snapshot; average cost is used if a mark is unavailable.</p></div></div><PositionTable positions={account?.positions??[]}/></section>}
{tab==='orders'&&<section className="surface paper-panel"><div className="section-head"><div><h2>Paper Order Management</h2><p>Open limit simulations can be cancelled. Filled and rejected records remain immutable evidence.</p></div></div><OrderTable orders={orders} tone={tone} onCancel={cancel}/></section>}
{tab==='performance'&&<PaperPerformancePanel mode="performance"/>}
{tab==='journal'&&<PaperPerformancePanel mode="journal"/>}
{tab==='risk'&&<><PaperRiskCenter/><section className="surface paper-panel" style={{marginTop:12}}><div className="section-head"><div><h2>Account Controls</h2><p>Paper-only maintenance controls.</p></div><ShieldCheck size={17}/></div><div className="paper-facts"><div><span>Real orders</span><b>BLOCKED</b></div><div><span>Broker routing</span><b>DISABLED</b></div><div><span>Validation rows</span><b>EXCLUDED</b></div><div><span>Promotion</span><b>EVIDENCE-GATED</b></div></div><button className="pulse-button" onClick={resetAccount} style={{marginTop:14}}><RefreshCw size={14}/> Reset Virtual Account</button><div className="tiny">Reset preserves historical snapshots and journal records.</div></section></>}</div>}
function Empty({text}:{text:string}){return <div className="paper-empty"><b>No data yet</b><span>{text}</span></div>}
function PositionTable({positions}:{positions:Position[]}){if(!positions.length)return <Empty text="No virtual positions exist yet."/>;return <div className="table-scroll"><table className="command-table"><thead><tr><th>Symbol</th><th>Qty</th><th>Avg Cost</th><th>Mark</th><th>Cost Basis</th><th>Market Value</th><th>Unrealized P&amp;L</th></tr></thead><tbody>{positions.map(p=><tr key={p.id}><td><b>{p.symbol}</b><small>{p.market}</small></td><td>{p.quantity.toLocaleString()}</td><td>{money(p.averageCost)}</td><td>{money(p.markPrice)}</td><td>{money(p.costBasis)}</td><td>{money(p.marketValue)}</td><td className={p.unrealizedPnl>=0?'good':'danger'}>{money(p.unrealizedPnl)}</td></tr>)}</tbody></table></div>}
function OrderTable({orders,tone,onCancel}:{orders:PaperOrder[];tone:(s:string)=>string;onCancel:(id:string)=>Promise<void>}){if(!orders.length)return <Empty text="The ledger is connected, but no live paper-order records exist."/>;return <div className="table-scroll"><table className="command-table paper-orders"><thead><tr><th>Time</th><th>Symbol</th><th>Side</th><th>Type</th><th>Requested</th><th>Filled</th><th>Req. Price</th><th>Fill Price</th><th>Fee</th><th>Slippage</th><th>Status</th><th>Action</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{new Date(o.created_at).toLocaleString()}</td><td><b>{o.symbol}</b><small>{o.market??'—'}</small></td><td>{o.side}</td><td>{o.order_type??'market'}<small>{o.time_in_force??'day'}</small></td><td>{Number(o.requested_qty).toLocaleString()}</td><td>{Number(o.filled_qty).toLocaleString()}</td><td>{o.requested_price==null?'—':money(Number(o.requested_price))}</td><td>{o.average_fill_price==null?'—':money(Number(o.average_fill_price))}</td><td>{money(Number(o.fee_amount??0))}</td><td>{o.slippage_bps==null?'—':`${Number(o.slippage_bps).toFixed(2)} bps`}</td><td><span className={`badge ${tone(o.status)}`}>{o.status.replaceAll('_',' ')}</span></td><td>{['open','pending','partially_filled'].includes(o.status)?<button className="icon-button" aria-label="Cancel paper order" onClick={()=>void onCancel(o.id)}><XCircle size={14}/></button>:<span className="tiny">—</span>}</td></tr>)}</tbody></table></div>}
