'use client';
import { useRef, useState } from 'react';
import { Send, ShieldCheck } from 'lucide-react';
import styles from './paper-order-ticket.module.css';

type Result={ok:boolean;error?:string;orderId?:string;symbol?:string;side?:string;quantity?:number;fillPrice?:number;simulation?:{estimatedOneWayCostBps:number;estimatedFillProbabilityPct:number;estimatedCapacityNotional:number;capacityExceeded:boolean;discontinuityRisk:string}};

export function PaperOrderTicket({onComplete}:{onComplete:()=>Promise<void>}){
 const[symbol,setSymbol]=useState('');const[side,setSide]=useState<'buy'|'sell'>('buy');const[quantity,setQuantity]=useState(100);const[orderType,setOrderType]=useState<'market'|'limit'>('market');const[limitPrice,setLimitPrice]=useState('');const[busy,setBusy]=useState(false);const[result,setResult]=useState<Result|null>(null);const retryKey=useRef<string|null>(null);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setResult(null);const idempotencyKey=retryKey.current??crypto.randomUUID();retryKey.current=idempotencyKey;try{const r=await fetch('/api/paper/orders',{method:'POST',headers:{'content-type':'application/json','idempotency-key':idempotencyKey},body:JSON.stringify({symbol,side,quantity:Number(quantity),orderType,limitPrice:orderType==='limit'?Number(limitPrice):undefined})});retryKey.current=null;const body=await r.json().catch(()=>({}));setResult(body);if(r.ok){setSymbol('');await onComplete()}}catch(e){setResult({ok:false,error:e instanceof Error?e.message:'paper_order_failed'})}finally{setBusy(false)}}
 return <div className={styles.grid}><form className={`surface paper-panel ${styles.ticket}`} onSubmit={submit}><div className="section-head"><div><h2>Paper Order Ticket</h2><p>Simulation only. Requires an unlocked Mercury admin session.</p></div><ShieldCheck size={17}/></div><div className={styles.formGrid}><label>Symbol<input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="Ticker" maxLength={16} required/></label><label>Side<select value={side} onChange={e=>setSide(e.target.value as 'buy'|'sell')}><option value="buy">Buy</option><option value="sell">Sell</option></select></label><label>Quantity<input type="number" min="0.000001" step="any" value={quantity} onChange={e=>setQuantity(Number(e.target.value))} required/></label><label>Order type<select value={orderType} onChange={e=>setOrderType(e.target.value as 'market'|'limit')}><option value="market">Market simulation</option><option value="limit">Limit simulation</option></select></label>{orderType==='limit'&&<label className={styles.wide}>Limit price<input type="number" min="0.000001" step="any" value={limitPrice} onChange={e=>setLimitPrice(e.target.value)} required/></label>}</div><div className={styles.boundary}><b>NO BROKER ROUTING</b><span>The request is evaluated against warehouse market snapshots, liquidity capacity and virtual account state only.</span></div><button className="pulse-button" disabled={busy}><Send size={14}/>{busy?'Simulating…':'Submit Paper Order'}</button></form><section className="surface paper-panel"><div className="section-head"><div><h2>Simulation Result</h2><p>Fill and liquidity diagnostics.</p></div></div>{!result?<div className={styles.resultEmpty}><b>Ready for simulation</b><span>Submit a paper order to see fill price, slippage, capacity and discontinuity risk.</span></div>:result.ok?<div className="paper-facts"><div><span>Order</span><b>{result.orderId}</b></div><div><span>Simulated fill</span><b>${Number(result.fillPrice??0).toFixed(4)}</b></div><div><span>Slippage</span><b>{result.simulation?.estimatedOneWayCostBps?.toFixed(2)??'—'} bps</b></div><div><span>Fill probability</span><b>{result.simulation?.estimatedFillProbabilityPct?.toFixed(1)??'—'}%</b></div><div><span>Capacity</span><b>${Number(result.simulation?.estimatedCapacityNotional??0).toLocaleString()}</b></div><div><span>Discontinuity</span><b>{result.simulation?.discontinuityRisk??'—'}</b></div></div>:<div className={styles.resultEmpty}><b className="danger">Order rejected</b><span>{(result.error??'unknown_error').replaceAll('_',' ')}</span>{result.simulation&&<small>Estimated capacity ${Number(result.simulation.estimatedCapacityNotional??0).toLocaleString()} · discontinuity {result.simulation.discontinuityRisk}</small>}</div>}</section></div>
}
