import { getSql } from '@/lib/db';
import { countSurvivors, summarizeProvenance } from '@/lib/performance/provenance';

export async function getHistoricalTwins(opportunityId:string,limit=20){
 const sql=getSql();if(!sql)return{available:false as const,reason:'database_not_configured' as const,twins:[]};
 try{
 const rows=await sql`WITH target AS (SELECT o.*,sf.return_5d,sf.volatility_20d,sf.volume_ratio_20d,sf.range_pct,sf.trend_20d,sf.drawdown_20d FROM opportunities o JOIN securities ts ON ts.id=o.security_id LEFT JOIN setup_fingerprints sf ON sf.opportunity_id=o.id WHERE o.id=${opportunityId} AND ts.id NOT LIKE 'validation:%' LIMIT 1),scored AS(SELECT o.id,o.security_id,s.symbol,o.state,o.action,o.alpha,o.gem,o.wave,o.asymmetry,o.catalyst,o.social,o.liquidity,o.trap_risk,o.peak_risk,o.confidence,o.observed_at,oo.return_15m,oo.return_60m,oo.return_1d,oo.mfe_60m,oo.mae_60m,sf.return_5d,sf.volatility_20d,sf.volume_ratio_20d,sf.range_pct,sf.trend_20d,sf.drawdown_20d,sqrt(power(o.alpha-t.alpha,2)+power(o.gem-t.gem,2)+power(o.wave-t.wave,2)+power(o.asymmetry-t.asymmetry,2)+power(o.catalyst-t.catalyst,2)+power(o.social-t.social,2)+power(o.liquidity-t.liquidity,2)+power(o.trap_risk-t.trap_risk,2)+power(o.peak_risk-t.peak_risk,2)+power(o.confidence-t.confidence,2)+power(coalesce(sf.return_5d,0)-coalesce(t.return_5d,0),2)*.5+power(coalesce(sf.volatility_20d,0)-coalesce(t.volatility_20d,0),2)*.15+power(coalesce(sf.volume_ratio_20d,0)-coalesce(t.volume_ratio_20d,0),2)*8+power(coalesce(sf.range_pct,0)-coalesce(t.range_pct,0),2)*.5+power(coalesce(sf.trend_20d,0)-coalesce(t.trend_20d,0),2)*.25+power(coalesce(sf.drawdown_20d,0)-coalesce(t.drawdown_20d,0),2)*.25)distance FROM opportunities o JOIN target t ON true JOIN securities s ON s.id=o.security_id LEFT JOIN opportunity_outcomes oo ON oo.opportunity_id=o.id LEFT JOIN setup_fingerprints sf ON sf.opportunity_id=o.id WHERE o.id<>t.id AND o.observed_at<t.observed_at AND o.state=t.state AND s.id NOT LIKE 'validation:%')SELECT * FROM scored ORDER BY distance ASC,observed_at DESC LIMIT ${Math.max(1,Math.min(100,limit))}`;
 // Pre-filter census. Counting candidates separately from the filtered result
 // is what makes the contamination check real: reporting a literal 0 could
 // never detect a regression in the NOT LIKE filter above.
 const [census]=await sql`SELECT count(*)::int candidate_rows,count(*) FILTER(WHERE s.id LIKE 'validation:%')::int synthetic_candidates FROM opportunities o JOIN securities s ON s.id=o.security_id WHERE o.id<>${opportunityId}`;
 const survivors=countSurvivors(rows as Array<{security_id?:string|null}>);
 const provenance=summarizeProvenance('live',{candidateRows:Number(census?.candidate_rows??0),syntheticCandidates:Number(census?.synthetic_candidates??0),syntheticSurviving:survivors.syntheticSurviving,liveSurviving:survivors.liveSurviving});
 const matured=rows.filter(r=>r.return_60m!=null),returns=matured.map(r=>Number(r.return_60m)).filter(Number.isFinite),mfe=matured.map(r=>Number(r.mfe_60m??0)).filter(Number.isFinite),mae=matured.map(r=>Number(r.mae_60m??0)).filter(Number.isFinite);
 return{available:true as const,mode:'shadow' as const,evidenceScope:'live' as const,liveEvidenceOnly:true as const,syntheticRows:provenance.syntheticSurviving,provenanceSafe:provenance.provenanceSafe,provenance,capitalExecutionEnabled:false as const,opportunityId,twinCount:rows.length,matured60m:returns.length,hitRate60mPct:returns.length?Number((returns.filter(v=>v>0).length/returns.length*100).toFixed(2)):0,averageReturn60mPct:returns.length?Number((returns.reduce((a,b)=>a+b,0)/returns.length).toFixed(2)):0,averageMfe60mPct:mfe.length?Number((mfe.reduce((a,b)=>a+b,0)/mfe.length).toFixed(2)):0,averageMae60mPct:mae.length?Number((mae.reduce((a,b)=>a+b,0)/mae.length).toFixed(2)):0,similarityModel:'opportunity-plus-market-fingerprint-v2',twins:rows,measuredAt:new Date().toISOString()};
 }catch{return{available:false as const,reason:'historical_replay_schema_not_initialized' as const,twins:[]};}
}
